# Generated by Django 3.0.1 on 2019-12-23 14:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20191223_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimages',
            name='pub_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
